sudo: required
services:
  - docker

before_install:
  - docker build -t vbfdt7/client_test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true vbfdt7/client_test npm test

after_success:
  - docker build -t vbfdt7/multi_client:1.0.0 ./client
  - docker build -t vbfdt7/multi_nginx:1.0.0 ./nginx
  - docker build -t vbfdt7/multi_server:1.0.0 ./server
  - docker build -t vbfdt7/multi_worker:1.0.0 ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vbfdt7/multi_client:1.0.0
  - docker push vbfdt7/multi_nginx:1.0.0
  - docker push vbfdt7/multi_server:1.0.0
  - docker push vbfdt7/multi_worker:1.0.0
