sudo: required
services:
  - docker

before_install:
  - docker build -t yunhe/client_test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true yunhe/client_test npm test

after_success: 
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdint
  - docker push vbfdt7/multi-images:multi-client
  - docker push vbfdt7/multi-images:multi-nginx
  - docker push vbfdt7/multi-images:multi-server
  - docker push vbfdt7/multi-images:multi-worker
